README.rst

Update description and adds website, however remove onadata reference

[WIP] Update description and adds website

---

onadata/apps/fieldsight/viewsets/FieldsightFcmViewset.py

response to 200 ok if dev id is not found in the database.

response to 200 if not found dev id

---

onadata/apps/fsforms/utils.py

Added key site_level_form on flagged form

site level form notification

---

onadata/apps/fsforms/views.py

Version wise instance detail page.

instance detail page version wise

---

onadata/apps/api/viewsets/xform_viewset.py
onadata/apps/fsforms/tasks.py
onadata/apps/fsforms/views.py

If any questions are deleted in latest version. old submission have older questions.

version wise submission detail page

---

onadata/apps/viewer/tasks.py
onadata/libs/utils/export_tools.py

Db connection removed from loops.

A faster way to create xls report.

---

onadata/apps/fieldsight/rolemixins.py
onadata/apps/fsforms/views.py

Checks permission to flag in object level

permission check on flagging submission

---

onadata/apps/fsforms/tasks.py
onadata/libs/utils/fieldsight_tools.py

Safe clone

---

onadata/apps/fieldsight/viewsets/FieldsightFcmViewset.py
onadata/libs/utils/logger_tools.py

got IntegrityError: duplicate key value violates unique constraint "fcm_device_reg_id_key" in fcm/add api.

103 integrity error fcm

---

onadata/apps/fieldsight/templates/fieldsight/organization_dashboard.html
onadata/apps/fieldsight/views.py
onadata/apps/users/templates/users/profile.html

user profile design enhancement

114 user profile design

---

onadata/apps/fieldsight/views.py
onadata/apps/users/templates/users/profile.html

Search Button not working for User Search on the Org and Project Level

[#112]-fixed user search in organization,project and site level

---

onadata/apps/fieldsight/templates/fieldsight/roles_dashboard.html
onadata/apps/fieldsight/views.py
onadata/apps/users/templates/users/userprofile_form.html
onadata/apps/users/views.py

Disabled notifications,Tasks, forms if user do not have profile. User profile is mandatory.

 Disabled notifications,Tasks, forms if user do not have profile. User profile is mandatory.

---

onadata/apps/fv3/util.py
onadata/apps/fv3/views.py

util to count db and timing of function

---

onadata/apps/fieldsight/urls.py
onadata/apps/users/middleware.py

Removed unwanted if condition checks from middleware. Required request parameters are preserved.

Middleware clear

---

onadata/apps/fieldsight/viewsets/FieldsightFcmViewset.py
onadata/apps/fsforms/utils.py

fcm clean up

---

onadata/apps/fv3/views.py

updated_date url parm to get updated datas.

deleted data only when last_updated date is passed

---

onadata/apps/fsforms/management/commands/create_xform_history.py
onadata/apps/fsforms/serializers/ConfigureStagesSerializer.py
onadata/apps/fsforms/urls.py
onadata/apps/fsforms/views.py
onadata/apps/fsforms/viewsets/ConfigureStageViewset.py
onadata/apps/users/viewsets.py

Instance Detail Page api.
This will give data for js page to create instance detail.

Detail api

---

onadata/apps/fieldsight/migrations/0079_auto_20190522_1304.py
onadata/apps/fsforms/fieldsight_logger_tools.py
onadata/apps/fsforms/migrations/0071_editedsubmission.py
onadata/apps/fsforms/models.py
onadata/apps/fsforms/viewsets/FSXFormSubmissionApiViewset.py

Link edited submission to old flagged one

edited submissions logs

---

onadata/apps/fsforms/serializers/FieldSightXFormSerializer.py

manifiest url

---

onadata/apps/fieldsight/views.py

Invitation to new users fixed from organization and project level.

---

kobocat-template/static/js/fieldsight/remove_supervisor_roles.js

[#225]-fixed roles showing up in dropdown, converting string to int.

---

onadata/apps/eventlog/migrations/0052_auto_20190614_1343.py
onadata/apps/eventlog/migrations/0053_auto_20190617_1034.py
onadata/apps/eventlog/migrations/0054_auto_20190617_1116.py
onadata/apps/eventlog/models.py
onadata/apps/fsforms/models.py
onadata/apps/fsforms/share_xform.py
onadata/apps/fsforms/tasks.py
onadata/apps/fv3/permissions/xform.py
onadata/apps/fv3/serializers/FormSerializer.py
onadata/apps/fv3/urls.py
onadata/apps/fv3/viewsets/FormsViewset.py

1. Share form api for project managers and organization admin of respective project.
2. Share form api for team(project managers and org admin) of given organization.
3. Permissions for share form.

Form share api to individuals

---

onadata/apps/eventlog/migrations/0055_auto_20190620_1032.py
onadata/apps/eventlog/models.py
onadata/apps/fsforms/management/commands/share_xform_managers.py
onadata/apps/fsforms/share_xform.py
onadata/apps/fsforms/tasks.py
onadata/apps/fv3/serializers/FormSerializer.py
onadata/apps/fv3/urls.py
onadata/apps/fv3/viewsets/FormsViewset.py

Api to clone a form.
**URL pattern:**
`/fv3/api/clone`
- Takes *FieldSight form id as request data*
{
"form": <fieldsight_xform_id>  # pass xform id or fieldsight xform id here???
}
- clones the form as specified to the user taken from `request.user`
- created a new `CeleryTaskProgress` type to suit the api cloning of form
- created a new task `api_clone_form`

Clone form api

---

onadata/apps/fv3/permissions/xform.py
onadata/apps/fv3/serializers/FormSerializer.py
onadata/apps/fv3/urls.py
onadata/apps/fv3/viewsets/FormsViewset.py

1. api for deleting myform. (creates an object of DeletedXForm **not directly deleting the xform**)
2. permissions classes for deleting forms and adding languages in forms.
3. myforms api modified only to show not deleted forms.

Myform delete api

---

onadata/apps/fv3/serializers/FormSerializer.py
onadata/apps/fv3/urls.py
onadata/apps/fv3/viewsets/FormsViewset.py

Get the list of projects to share a form to.
**url pattern:**
`/fv3/api/form/projects/`

List of projects to share a form

---

onadata/apps/fsforms/forms.py

Show the forms shared to the user in the assign form list of project/site.

[#296] - show shared form list in assign form of project/site

---

onadata/apps/fieldsight/models.py

Created a function to get all the meta attributes that have been deleted.

function to check the deleted meta attributes in project

---

onadata/apps/fsforms/utils.py
onadata/apps/fsforms/views.py

Add **ENKETO_PREVIEW_URL = ENKETO_URL + os.environ.get('ENKETO_API_ENDPOINT_PREVIEW', '/preview')** to local_settings.py.

[#311]-Initial-fix: enketo form preview

---

onadata/apps/fieldsight/utils/project_meta_attributes.py

Creates id in meta attribute if not exists

project metas clean

---

onadata/apps/fsforms/migrations/0085_schedule_frequency.py
onadata/apps/fsforms/models.py
onadata/apps/fv3/serializers/FormSerializer.py
onadata/apps/fv3/serializers/manage_forms.py

schedule form add frequency

---

onadata/apps/fv3/viewsets/manage_forms.py

manage forms unassigned sites filter

---

LICENSE

changes in license

---

onadata/apps/fsforms/migrations/0092_organizationformlibrary.py
onadata/apps/fsforms/models.py
onadata/apps/fsforms/tasks.py
onadata/apps/fv3/serializers/SuperOrganizationSerializer.py
onadata/apps/fv3/urls/super_organization.py
onadata/apps/fv3/views.py
onadata/apps/fv3/viewsets/SuperOrganizationViewset.py
onadata/apps/fv3/viewsets/TeamViewSet.py

Organization Library forms.
library forms  in project  for new project

Org form library

---

onadata/apps/fieldsight/tasks.py
onadata/apps/fieldsight/utils/google_sheet_create.py
onadata/apps/fieldsight/views.py
onadata/settings/local_settings.sample.py

upload sites async task

---

onadata/apps/fieldsight/generatereport.py
onadata/apps/fsforms/views.py
onadata/apps/remote_app/views.py

pdf-fix
pin token debug
submission flag

Version miss
